### ISSUE TITLE
Rails dependency indirectly required

### ISSUE THREAD

**Issue by guy-silva** [jamis/bulk_insert#10]
I might be wrong but on [bulk_insert/lib/bulk_insert/worker.rb:67](https://github.com/jamis/bulk_insert/blob/824e0bb8d88e431db8eefee6330d0cc55a4379fc/lib/bulk_insert/worker.rb#L67) you seem to be requiring rails instead of activerecord and that, when saving a worker causes: 

``` ruby
*** NameError Exception: uninitialized constant BulkInsert::Worker::Rails
```

I discovered it while using the gem in a project where I only use ActiveRecord.
That can be bypassed if a module `Rails` that respond to `version` is defined inside the project

**Comment by brandonsturgeon** [comment]
Currently using Sinatra with just Activerecord, and I'm able to bulk_insert just fine

**Comment by jamis** [comment]
Yeah, my bad, this issue has been fixed, but I neglected to update this issue.

**Comment by brandonsturgeon** [comment]
No problem! Thanks for getting that fixed up. bulk_insert is saving me minutes per run of my script, thanks!

I got here from your [blog post](http://weblog.jamisbuck.org/2015/10/10/bulk-inserts-in-activerecord.html), by the way!
