### ISSUE TITLE
Make it work properly without *_id when it's a relation

### ISSUE THREAD

**Issue by oswaldoferreira** [jamis/bulk_insert#16]
When not using *_id on a relation when building the attr hash, `.bulk_insert` runs without errors, but no records are inserted. 

Proposal:

1. Take advantage of AR to discover if it's a relation and properly format with *_id when building the SQL
2. Throw an error if something goes wrong

**Comment by akanshmurthy** [comment]
+ 1.

No errors/exceptions/rollbacks thrown but no records are inserted if relations are present and a non-id attribute is the main insert.

**Comment by mberlanda** [comment]
hey,can you put an example just to start writing some tests for this feature? what would be exactly the expected behavior?

**Comment by jamis** [comment]
There hasn't been any activity on this for a few months, so I'm going to close this issue. If it is still a problem, please feel free to reopen it.
