### ISSUE TITLE
Support PostgreSQL 9.5 ON CONFLICT when using ignore: true flag

### ISSUE THREAD

**Issue by tehPlayer** [jamis/bulk_insert#23]
Currently when trying to use ignore: true, it uses INSERT IGNORE INTO which is incorrect PG syntax. Since PG 9.5, there is working syntax:

https://wiki.postgresql.org/wiki/What%27s_new_in_PostgreSQL_9.5#INSERT_..._ON_CONFLICT_DO_NOTHING.2FUPDATE_.28.22UPSERT.22.29

**Comment by tehPlayer** [comment]
I read code on master and found its already supported ; )

**Comment by jamis** [comment]
Yeah, sorry I haven't cut a new gem for awhile. I've been waiting for a PR to be updated, but it doesn't look like the author is going to get to it. I'll see about releasing an updated gem soon.
