### ISSUE TITLE
Error when default column names are different

### ISSUE THREAD

**Issue by nishantkumar1292** [jamis/bulk_insert#25]
I am using bulk insert in Rails Table.
My `id` column is named as `PRODUCT_ID` and `created_at` and `updated_at` are respectively `RECORD_CREATE_DATE` and `RECORD_UPDATE_DATE`.

The bulk insert takes these values as NULL and I get an error because these fields have **not null constraint**.

How do I solve these?

**Comment by mberlanda** [comment]
Hi @nishantkumar1292, can you post your `schema.rb` (at least the relevant table), the adapter your using and eventually a test to reproduce your issue?

**Comment by jamis** [comment]
There hasn't been any activity on this for a few months, so I'm going to close this issue. If it is still a problem, please feel free to reopen it.
