### ISSUE TITLE
Support PostgreSQL 9.5 ON CONFLICT DO UPDATE

### ISSUE THREAD

**Issue by sobstel** [jamis/bulk_insert#34]
I can see it's supported for MySQL but there's DO NOTHING for Postgres. Any reason for that?

It's supported since 9.5: https://wiki.postgresql.org/wiki/What%27s_new_in_PostgreSQL_9.5#INSERT_..._ON_CONFLICT_DO_NOTHING.2FUPDATE_.28.22UPSERT.22.29

**Comment by jamis** [comment]
Probably, the person who submitted the original PR implemented it only for MySQL. Please do submit a PR adding the PostgreSQL support!
