### ISSUE TITLE
Add support for RETURNING

### ISSUE THREAD

**Issue by gogiel** [jamis/bulk_insert#4]
Some DBs support `RETURNING` in `INSERT`.
Postgres example: http://www.postgresql.org/docs/9.1/static/sql-insert.html

**Comment by jamis** [comment]
It looks like `RETURNING` is specific to PostgreSQL. From that page you linked:

    the RETURNING clause is a PostgreSQL extension

If you can think of a clean way to introduce `RETURNING` without muddying the API or over-complicating the implementation, I'd be willing to consider a pull-request for this.
