### ISSUE TITLE
Deprecate the lib since Rails 6.x

### ISSUE THREAD

**Issue by sobstel** [jamis/bulk_insert#47]
Rails 6.x brings a native support for bulk inserts and upserts. 

- https://github.com/rails/rails/pull/35077
- https://blog.saeloun.com/2019/11/26/rails-6-insert-all.html

This lib makes sense for <6.x only now.

**Comment by mberlanda** [comment]
:wave: @sobstel 

Thank you very much opening this issue.

Did you manage to check if the scope of this gem is fully covered by the ActiveRecord >= 6 implementation?

If it is the case, we may actually consider to restrict the supported versions.

**Comment by sobstel** [comment]
I didn't compare it 1-to-1, but I can see it has both support for postgres' `returning` and `unique_by`. 

I think the best (rr rather laziest) is to update docs to mention AR6 offers similar functionality and use `bulk_insert` only if it's missing anything.
