### ISSUE TITLE
bulk_insert version 1.8.1 doesn't play nice with activerecord and mysql2

### ISSUE THREAD

**Issue by grdw** [jamis/bulk_insert#67]
I have created a test project here: https://github.com/grdw/bulk_insert_bug 

When cloning said project and running `ruby main.rb` the following bug appears:

```
﻿﻿﻿Traceback (most recent call last):
	23: from main.rb:18:in `<main>'
	22: from /Users/gerard/.ruby/gems/bulk_insert-1.8.1/lib/bulk_insert.rb:18:in `bulk_insert'
/Users/gerard/.ruby/gems/bulk_insert-1.8.1/lib/bulk_insert/worker.rb:112:in `block (2 levels) in compose_insert_query': 
undefined method `type_cast_from_column' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x00007ffc9488e788> (NoMethodError)
```

It seems something has changed from ActiveRecord 6.0.3.4 to 6.1.0.

**Comment by mberlanda** [comment]
Version 1.8.2 was bumped today. Can you confirm the issue is fixed?

**Comment by grdw** [comment]
@mberlanda yes, this seems to work. Thanks for the fix 👍
