### ISSUE TITLE
Support Rails 5

### ISSUE THREAD

**Issue by kaluznyo** [jamis/bulk_insert#7]
Rails 5 is almost here ! 
http://weblog.rubyonrails.org/2016/2/27/Rails-5-0-beta3/

Plan to support it ?

**Comment by jamis** [comment]
Sure, I'd love to see it supported. If there is anything specific broken, let me know--or better yet, shoot me a pull request. :)

**Comment by jamis** [comment]
In the absence of anything specific reported broken, I'm going to close this issue. If there is something specific that needs to do to support Rails 5, feel free to reopen, or--better yet--submit a pull request. Thanks!
